version: '3.8'

services:
  frontend-license-key:
    build:
      context: .
      dockerfile: Dockerfile
      # Truyền biến vào lúc build (Quan trọng cho Vite)
    container_name: InfographAI
    restart: always
    ports:
      - "3000:8080"  # Map cổng 8080 trong container ra cổng 3005 của server